name: CI/CD Pipeline - Docker y Render

on:
  push:
    branches:
      - main  

env:
  DOCKER_IMAGE_NAME: entrega-continua
  DOCKER_HUB_USER: ${{ secrets.DOCKER_USERNAME }}
  IMAGE_TAG: ${{ github.sha }}

jobs:
  build-and-push:
    name: üèóÔ∏è Build y Push a Docker Hub
    runs-on: ubuntu-latest
    steps:
    
      - name: 1. Checkout del Repositorio
        uses: actions/checkout@v4

      - name: 2. Iniciar Sesi√≥n en Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ env.DOCKER_HUB_USER }}
          password: ${{ secrets.DOCKER_PASSWORD }} # Utiliza el Token de Acceso Personal

      - name: 3. Configurar Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: 4. Construir y Subir la Imagen
        uses: docker/build-push-action@v5
        with:
          context: .
          push: true
          tags: |
            ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:${{ env.IMAGE_TAG }}
            ${{ env.DOCKER_HUB_USER }}/${{ env.DOCKER_IMAGE_NAME }}:latest # Sube la versi√≥n m√°s reciente

  deploy-to-render:
    name: üöÄ Despliegue a Render.com
    runs-on: ubuntu-latest
    needs: build-and-push 
    steps:
      - name: 1. Despliegue Autom√°tico en Render.com
        uses: fjogeleit/http-request-action@v1
        with:
          url: 'https://api.render.com/v1/services/${{ secrets.RENDER_SERVICE_ID }}/deploys'
          method: 'POST'
          customHeaders: '{"Accept": "application/json", "Authorization": "Bearer ${{ secrets.RENDER_API_KEY }}"}'
          contentType: 'application/json'
          data: '{ "clearCache": "do_not_clear" }'